### ISSUE TITLE
SDK升级到5.1.3后在Vivo Y66上报错 No implementation found for int com.ez.stream.NativeApi.initSDK(int)  (tried Java_com_ez_stream_NativeApi_initSDK and Java_com_ez_stream_NativeApi_initSDK__I)

### ISSUE THREAD

**Issue by wl386123298** [Ezviz-Open/EzvizSDK-Android#16]

**Comment by Ezviz-Open** [comment]
如果在SDK集成过程或使用中遇到问题，可以通过官网创建工单来联系我们，不要在git上反馈问题。请在工单中提供如下内容：
1.是否已在Demo上复现，偶现还是必现
2.SDK版本号
3.问题详细描述+demo启动至问题复现过程的日志
4.提供appKey+accessToken+设备序列号

If you encounter problems during SDK integration or use, you can contact us by creating a work order on the official website. Don't feed back problems on GIT. Please provide the following in the work order:

Whether it has been reproduced on demo, occasional or mandatory
SDK version number
Detailed description of the problem + demo log of the process from starting to reproducing the problem
Provide appkey + accesstoken + device serial number
官网地址/official website address：https://open.ys7.com/cn/s/index
操作引导/Operation guidance：https://www.yuque.com/u2038998/qa5rn7/tifiv5

**Comment by lucasbarretoluz** [comment]
我在调用initSDK方法时遇到相同的错误。
