### ISSUE TITLE
Can't authorize in EzVIZ SDK using own authorization server

### ISSUE THREAD

**Issue by jizoquval** [Ezviz-Open/EzvizSDK-Android#6]
Hi we are using your Android SDK v4.14.0 and try to setup authorization with our own server using flow which your describe in docs (https://open.ys7.com/doc/zh/book/index/account-api.html and https://open.ys7.com/doc/zh/book/4.x/android-sdk.html)

**How we tried to authorize**

1. Our server get access token by account credentials by this api _https://open.ezvizlife.com/api/lapp/token/get_;
This Api returns: 
```
{
    "code": "200",
    "data": {
        "accessToken": "at.**********",
        "areaDomain": "https://iusopen.ezvizlife.com",
        "expireTime": 1600937237973
    },
    "msg": "Operation succeeded"
}
```
2. Server create user sub-account by this api _https://iusopen.ezvizlife.com/api/lapp/ram/account/create_;
And received account info 
```
{
    "code": "200",
    "data": {
        "accountId": "*********"
    },
    "msg": "Operation succeeded"
}
```
3. Our server get sub account access token and return it to out application 
_https://iusopen.ezvizlife.com/api/lapp/ram/token/get_;
This api returns:
```
{
    "code": "200",
    "data": {
        "accessToken": "ra.5v***********",
        "expireTime": 1600931893657,
        "areaDomain": "https://iusopen.ezvizlife.com"
    },
    "msg": "Operation succeeded"
}

```
4. After it we set received access token to Android mobile app to EZVIZ SDK using:
`EZGlobalSDK.getInstance().setAccessToken("ra.5v**********");`

5. Your SDK try to get server info  _https://open.ezvizlife.com/api/server/info_ but always get this error:
` {"resultCode":"10002","resultMsg":"AccessToken expired or error."}`

I see only one difference with your docs what we use this link _https://open.ezvizlife.com/api/lapp/token/get_ in step one instead of _https://open.ys7.com/api/lapp/token/get_ . But we can't use link from your docs because this returns  an error 
```
{
    "msg": "appKey不存在",
    "code": "10017"
}
```

What are we doing wrong?

**Comment by c-reschke** [comment]
I have the same problem. Any solution?

**Comment by jizoquval** [comment]
@c-reschke We found solution. Our keys was specified for North America region, but our developers location is Russia. So using VPN on the phone resolve problem with authorization.

**Comment by c-reschke** [comment]
@NinjaValentin I will test with VPN.
